/* make input saveable when button is pressed
Make current day display at top of page
color code timeblocks*/

const input8 = $(`input8`).val()
const input9 = $(`input9`)
const input10 = $(`input10`)
const input11 = $(`input11`)
const input12 = $(`input12`)
const input1 = $(`input1`)
const input2 = $(`input2`)
const input3 = $(`input3`)
const input4 = $(`input4`)
const input5 = $(`input5`)

function saveInput(){

};

$(`#btn8`).on("click", saveInput())
l$(`#btn9`).on("click", saveInput())
$(`#btn10`).on("click", saveInput())
$(`#btn11`).on("click", saveInput())
$(`#btn12`).on("click", saveInput())
$(`#btn1`).on("click", saveInput())
$(`#btn2`).on("click", saveInput())
$(`#btn3`).on("click", saveInput())
$(`#btn4`).on("click", saveInput())
$(`#btn5`).on("click", saveInput())

